name: CallPolice debug

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      ## run unit tests
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  build:
    name: Build app
    runs-on: ubuntu-18.04

    steps:
      ## Initial setup.
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Check if we can build.
      - name: Build with Gradle
        run: bash ./gradlew build

      ## Cache gradle dependencies for faster builds
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      ## Generate debug/test apk
      - name: Generate debug build
        run: bash ./gradlew --no-daemon -g /opt/gcache :app:assembleDebug --stacktrace

      #rename apk
      - name: Rename apk
        run: sudo mv app/build/outputs/apk/debug/*.apk app/build/outputs/apk/debug/callDebugPolice.apk

      ## Upload debug apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/


