name: CallPolice release

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-18.04

    steps:
      ## Initial setup.
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## run unit tests
      - name: Unit tests
        run:  bash ./gradlew test --stacktrace

  build:
    name: Build app
    runs-on: ubuntu-18.04

    steps:
      ## Initial setup.
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ## Cache gradle dependencies for faster builds
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      ## Check if we can build.
      - name: Build with Gradle
        run: sudo ./gradlew build

      ## Generate production apk
      - name: Generate signed release build
        run: sudo ./gradlew --no-daemon -g /opt/gcache assembleRelease --stacktrace

      ## Upload release apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/callPolice-release.apk


